sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -d -k "$authdecrypt" -in src/auth.json.enc -out src/auth.json
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp yarn
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- yarn add sqlite
install:
- yarn install
script:
- yarn run lintfix
- yarn run lint
- yarn run test
notifications:
  email: false
env:
  global:
    secure: sFwkRPop5T7M77dAkAj9+KHZr33jwG7ax8yF/fTxOut1q2+H74EhTr461kdYdFBk30sWrw/t+HdyUbqbnHjh+wihW2GdEMfwHnOtOnnnhKPpKQ/Vq/09iTAjL3r4C1HBa88Ub4Hejw917qbmDAsofZqeDSF5EYXO7YDGHOo+40PlnMoWIhJLPWMikgkZujUhWOjKHXIQuzitlCz0rtUS8Q/QkW31YAOx6sfzpqK7/rjTFhHEPOiWtKmve5BjuOKHer+EvHU63UqoFoSz3tLMUNMByD3NJ1Rkvk6ZOKFnUpjE6EC7aOZuSioFbrM2uelq9aw1hvAaXwyzqxxyj7y5gmcQpot1BU+/ybr2WN2mK3DqfysSNqWRlp94L+MLOKQLUFuBWanq4LEJb8bnoiPfDkMoURavZU+9kDopEZwDFbveHG4JBFCpv/DLadmy82r1r8fJxr49tiMV1s/nvwfVkDkZ3d4gUsCg69VPuBqoLUQzNE9P7uOKGLip7I6/gGCC+1XnDGLHipmtCjD/NTyHC2sFiDsU379z0wVHSta2YVaRgBkXfW5OwAa6YokQNuBXVbqE9W1fdczmy9K8XzcLvareJljAkJft2nglppQJuGJBjju8N82c3NNkXxu8nn/ATibxHbCfFpvgpwEqnFxmyIe5rVOr46fp/LdA8xbMvrY=
